version: '3.9'
services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db
    ports:
      - '27017:27017'
  
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://my-mongodb:27017/

  my_node_app:
    build: ./backend
    ports:
      - 7000:7000
    dockerfile: Dockerfile
    container_name: my_node_app
    environment:
      PORT: 4000
      MONGODB_URI: mongodb://mongo_db:27017
      DB_NAME: Docker
    depends_on:
      - mongo_db

  my_react_frontend:
    build: ./frontend
    dockerfile: Dockerfile
    container_name: my_react_frontend
    ports:
      - '3000:3000'
    depends_on:
      - my_node_app

  

volumes:
  mongo_db:
